flows:
  - "login/*"
  - "pickup_ordering/*"
  - "delivery_ordering/*"
# includeTags:
#   - "smokeTest"
# excludeTags:
#   - "smokeTest"
executionOrder:
    continueOnFailure: false # default is true
    flowsOrder:
        - verify member can login successfully
        - verify member can create a pickup order successfully
        - verify member can cancel a pickup order
        - verify member can create a delivery order successfully
        - verify member can cancel a delivery order
        - verify member can logout successfully
# notifications:
#   email:
#     enabled: true
#     onsSuccess: true
#     recipients:
#       - o.aly@getzeal.io