flows:
  - "ios/login/*"
  - "ios/booking/*"
includeTags:
  - "smokeTest"
# excludeTags:
#   - "smokeTest"
executionOrder:
    continueOnFailure: false # default is true
    flowsOrder:
        - Verify member can login successfully
        - Verify member can create a booking successfully
        - Verify member can cancel a booking
        - Verify member can logout successfully
notifications:
  email:
    enabled: true
    onsSuccess: true
    recipients:
      - o.aly@getzeal.io