flows:
  - "login/*"
  - "booking/*"
# includeTags:
#   - "smokeTest"
# excludeTags:
#   - "smokeTest"
executionOrder:
    continueOnFailure: false # default is true
    flowsOrder:
        - Booking Apps - Verify member can login successfully
        - Booking Apps - Verify member can create a booking successfully
        - Booking Apps - Verify member can cancel a booking
        - Booking Apps - Verify member can logout successfully
notifications:
  email:
    enabled: true
    onsSuccess: true
    recipients:
      - o.aly@getzeal.io