name: Android Maestro Tests

on:
  push:
    branches: [ main ]

jobs:
  maestro-android-tests:
    name: Run Maestro tests on Android emulator
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # Set up Android Emulator
      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          profile: pixel_7_pro
          emulator-options: -no-snapshot -no-audio -no-window
          disable-animations: true
          script: echo "Emulator started"

      # Wait for emulator to be ready
      - name: Wait for emulator to be ready
        run: |
          adb wait-for-device
          adb shell getprop sys.boot_completed | grep -m 1 '1'
          echo "Emulator is ready!"

      - name: Install Maestro CLI
        run: |
          curl -Ls https://get.maestro.mobile.dev | bash
          export PATH="$PATH:$HOME/.maestro/bin"
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH
    
      - name: Download Android APK
        run: |
          curl -L -o ChallazTopfade.apk "https://expo.dev/artifacts/eas/nucrjGpGXJXr6qWFugV7uS.apk"
        
      - name: Install APK on Emulator
        run: |
          adb install ChallazTopfade.apk

      - name: Run Maestro flow
        run: |
          maestro test android/