name: Run Maestro Flows on Android

on:
  # push:
  #   branches: [main]
  workflow_dispatch:

jobs:
  maestro-android:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download APK from Expo
        run: |
          curl -L "https://expo.dev/artifacts/eas/jZrydfYWfmK4GnYje3zX1x.apk" -o ChallazTopfade.apk

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Create and start emulator
        run: |
          echo "no" | avdmanager create avd -n test -k "system-images;android-31;google_apis;arm64-v8a" -d "pixel_7_pro"
          $ANDROID_HOME/emulator/emulator -avd test -no-window -no-audio -no-boot-anim &
          adb wait-for-device
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0

      - name: Install Maestro
        run: |
          brew tap mobile-dev-inc/tap
          brew install maestro
      
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"    
          
      - name: Install APK to Emulator
        run: |
          adb install ChallazTopfade.apk

      - name: Run Maestro Flows
        run: |
          maestro test android/