name: Run Maestro Flows on iOS (macOS runner)

on:
  # push:
  #   branches:
  #     - test
  workflow_dispatch:

jobs:
  maestro-test-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install Facebook IDB
        run: brew install facebook/fb/idb-companion

      - name: Install Maestro CLI
        run: |
          brew tap mobile-dev-inc/tap
          brew install maestro

      - name: Start iOS Simulator
        run: xcrun simctl boot "iPhone 15"
      - name: Set Maestro Timeout Environment Variable
        run: echo "MAESTRO_DRIVER_STARTUP_TIMEOUT=1000000" >> $GITHUB_ENV


      - name: Download iOS App for Simulator
        run: |
          curl -L -o ChallazTopfade.tar.gz "https://expo.dev/artifacts/eas/4iAHbRbn6mYJtzgR8otThu.tar.gz"
          tar -xvzf ChallazTopfade.tar.gz

      - name: Install iOS App
        run: xcrun simctl install "iPhone 15" ChallazTopfade.app
        
      - name: Run Maestro Flow
        run: maestro test ios/
