name: Run Maestro Flows on iOS

on:
  push:
    branches:
      - master

jobs:
  maestro-test-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install Facebook IDB
        run: brew install facebook/fb/idb-companion

      - name: Install Maestro CLI
        run: |
          brew tap mobile-dev-inc/tap
          brew install maestro

      - name: Start iOS Simulator
        run: xcrun simctl boot "iPhone 15"
      - name: Set Maestro Timeout Environment Variable
        run: echo "MAESTRO_DRIVER_STARTUP_TIMEOUT=1000000" >> $GITHUB_ENV



      - name: Download Expo Build
        run: |
          curl -o ChallazTopfade.app "https://expo.dev/accounts/challaz-topfade/projects/challaz-topfade/builds/5ecaea8e-bb42-415a-8b5d-60fb8921d0bd"

      - name: Install iOS App
        run: xcrun simctl install "iPhone 15" ChallazTopfade.app


        
      - name: Run Maestro Flow
        run: maestro test .
