name: Run Maestro Flows on iOS

on:
  push:
    branches:
      - master

jobs:
  maestro-test-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install Facebook IDB
        run: brew install facebook/fb/idb-companion

      - name: Clean and Reinstall Maestro CLI
        run: |
          rm -rf ~/.maestro
          curl -Ls https://get.maestro.mobile.dev | bash
      - name: following instruction
        run: export PATH="$PATH":"$HOME/.maestro/bin"
      - name: Add /usr/local/bin to PATH
        run: echo 'export PATH=$PATH:/usr/local/bin' >> $GITHUB_ENV
      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV
      - name: Verify Maestro Installation
        run: |
          which maestro
          maestro --version
      - name: Start iOS Simulator
        run: xcrun simctl boot "iPhone 15"

      - name: Run Maestro Flow
        run: maestro test .